# Generated by Django 6.0.3 on 2026-04-03 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10)),
                ('make', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('engine_capacity', models.IntegerField(blank=True, null=True)),
                ('year_of_manufacture', models.IntegerField()),
                ('mot_status', models.CharField(blank=True, max_length=50)),
                ('mot_expiry', models.DateField(blank=True, null=True)),
                ('tax_status', models.CharField(blank=True, max_length=50)),
                ('tax_due_date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
